### ISSUE TITLE
Add a new custom hook: useResizeObserver

### ISSUE THREAD

**Issue by baskvava** [Team-Grace/devgrace#11]
Hi,
I want to proposal an idea about adding a new custom hook library for ResizeObserver to observe the element of width and height. This custom hook will return the value of width and height.

This is the simple abstract idea for it.

```js
export function useResizeObserver(ref) {
    ....
    return { width: width, height: height };
}
```

Please provide any feedback or any question if you have concern on it. Thanks.

**Comment by ssi02014** [comment]
@baskvava 
I was planning to work on the useResizeObserver hook. Thank you 👍

**Comment by ssi02014** [comment]
https://github.com/Team-Grace/devgrace/pull/12  I'm working on something related. Please take note. 🙏

**Comment by ssi02014** [comment]
[useResizeObserver Code](https://github.com/Team-Grace/devgrace/blob/master/packages/react/src/hooks/useResizeObserver/index.ts)
[useResizeObserver Docs](https://team-grace.github.io/devgrace/docs/react/hooks/useResizeObserver/)

I've added the useResizeObserver custom hook, so I'm closing this issue.
Thank you. 👍

**Comment by baskvava** [comment]
Hi,
Thanks to let me know. I would recommend to provide a list for on going task in some where.
It could be the communication effectively.
